#!/usr/bin/env node
/* Scaffold a new yeet example project.
 *
 * Writes a starter directory laid out like the rest of `example/`:
 *
 *   <name>/
 *     <slug>.bpf.c   — minimal XDP noop with a ringbuf event
 *     main.js        — loads the object, attaches the prog, drains events
 *     README.md      — build + run instructions
 *
 * Run on the host (Node ≥ 18, no deps):
 *
 *   node example/bootstrap/bootstrap.js my-new-example
 *   node example/bootstrap/bootstrap.js my-new-example --dest example
 *   node example/bootstrap/bootstrap.js my-new-example --force
 *
 * After scaffolding, build the BPF object inside the Lima VM:
 *
 *   make vm
 *   lima/scripts/vm_shell.sh yeet.debian-13 \
 *     clang -O2 -g -target bpf -c <slug>.bpf.c -o <slug>.bpf.o
 *
 * Then point yeet at the new directory:
 *
 *   yeet run ./<dest>/<name>
 */

const fs = require("node:fs");
const path = require("node:path");

const args = process.argv.slice(2);
if (args.length === 0 || args.includes("-h") || args.includes("--help")) {
  usage(0);
}

let projectName;
let dest = ".";
let force = false;

for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === "--force" || a === "-f") {
    force = true;
  } else if (a === "--dest" || a === "-d") {
    dest = args[++i];
    if (!dest) usage(1, "--dest needs a path");
  } else if (a.startsWith("-")) {
    usage(1, `unknown flag: ${a}`);
  } else if (!projectName) {
    projectName = a;
  } else {
    usage(1, `unexpected positional: ${a}`);
  }
}

if (!projectName) usage(1, "missing project name");

const name = projectName;
const slug = toSlug(name);
const stem = toIdent(slug);
const target = path.resolve(dest, name);

if (fs.existsSync(target) && !force) {
  const entries = fs.readdirSync(target);
  if (entries.length > 0) {
    fail(`target ${target} exists and is not empty (pass --force to overwrite)`);
  }
}

fs.mkdirSync(target, { recursive: true });

const files = {
  [`${stem}.bpf.c`]: bpfTemplate(stem),
  "main.js": jsTemplate(name, stem),
  Makefile: makefileTemplate(stem),
  "README.md": readmeTemplate(name),
};

const executable = new Set(["main.js"]);

for (const [filename, contents] of Object.entries(files)) {
  const full = path.join(target, filename);
  if (fs.existsSync(full) && !force) {
    fail(`refusing to overwrite ${full} (pass --force)`);
  }
  fs.writeFileSync(full, contents, {
    mode: executable.has(filename) ? 0o755 : 0o644,
  });
  if (executable.has(filename)) fs.chmodSync(full, 0o755);
  console.log(`  wrote ${path.relative(process.cwd(), full)}`);
}

console.log("");
console.log(`Scaffolded ${name} at ${target}`);
console.log("");
console.log("Next steps:");
console.log(`  cd ${path.relative(process.cwd(), target) || "."}`);
console.log(`  make            # build ${stem}.bpf.o (run inside Lima on macOS)`);
console.log(`  ./main.js       # or: yeet run .`);

function usage(code, msg) {
  if (msg) console.error(`error: ${msg}\n`);
  const me = path.relative(process.cwd(), process.argv[1]) || "bootstrap.js";
  console.error(`usage: node ${me} <name> [--dest <dir>] [--force]`);
  console.error("");
  console.error("  <name>         project directory name (kebab-case recommended)");
  console.error("  --dest <dir>   parent directory to scaffold into (default: cwd)");
  console.error("  --force, -f    overwrite existing files");
  process.exit(code);
}

function fail(msg) {
  console.error(`error: ${msg}`);
  process.exit(1);
}

/* Normalize an arbitrary string to a kebab-case slug suitable for
 * filenames and a BPF object stem. */
function toSlug(s) {
  return s
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    || "example";
}

/* Slug → C identifier (underscores, leading digit guarded). */
function toIdent(slug) {
  const id = slug.replace(/-/g, "_");
  return /^[0-9]/.test(id) ? `_${id}` : id;
}

function bpfTemplate(ident) {
  return `// SPDX-License-Identifier: GPL-2.0
//
// Generated by example/bootstrap. Minimal XDP noop that emits a
// ringbuf event per packet and bumps a .bss counter. Replace with
// your own program logic.

#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "GPL";

struct ${ident}_event {
\t__u64 ts_ns;
\t__u32 ifindex;
\t__u32 len;
};

struct {
\t__uint(type, BPF_MAP_TYPE_RINGBUF);
\t__uint(max_entries, 1 << 16);
} events SEC(".maps");

__u64 packets_seen = 0;
const volatile __u32 event_budget = 16;

SEC("xdp")
int ${ident}_count(struct xdp_md *ctx)
{
\t__sync_fetch_and_add(&packets_seen, 1);

\tif (packets_seen > event_budget)
\t\treturn XDP_PASS;

\tstruct ${ident}_event *ev = bpf_ringbuf_reserve(&events, sizeof(*ev), 0);
\tif (!ev)
\t\treturn XDP_PASS;

\tev->ts_ns = bpf_ktime_get_ns();
\tev->ifindex = ctx->ingress_ifindex;
\tev->len = (__u32)(ctx->data_end - ctx->data);
\tbpf_ringbuf_submit(ev, 0);

\treturn XDP_PASS;
}
`;
}

function makefileTemplate(stem) {
  /* Mirrors the .PHONY/ARCH/clang/clean shape used by the existing
   * example Makefiles (honeypot, task-budget, arena-ring, …). */
  return `.PHONY: all clean

ARCH := $(shell uname -m | sed 's/aarch64/arm64/; s/x86_64/x86/')

all: ${stem}.bpf.o

${stem}.bpf.o: ${stem}.bpf.c
\tclang -O2 -g -target bpf \\
\t\t-D__TARGET_ARCH_$(ARCH) \\
\t\t-I/usr/include/$(shell uname -m)-linux-gnu \\
\t\t-c $< -o $@

clean:
\trm -f ${stem}.bpf.o
`;
}

function jsTemplate(name, stem) {
  const objStem = stem.slice(0, 8);
  return `#!/usr/bin/env -S yeet run
/* ${name} — generated by example/bootstrap.
 *
 * Replace this header with a real description once the example does
 * something. Build the object first (inside Lima on macOS):
 *
 *   make
 *
 * Then run (the file is chmod +x, shebang resolves to yeet):
 *
 *   ./main.js          # or
 *   yeet run ./example/${name}
 */

import bpf from "./${stem}.bpf.o";
import { DataSec, RingBuf } from "yeet:bpf";

const RUN_SECONDS = 10;
const POLL_INTERVAL_MS = 1_000;

/* libbpf names the implicit data-section maps \`<obj>.bss\` / \`<obj>.data\`
 * where \`<obj>\` is the BPF object's stem truncated to 8 chars. For
 * \`${stem}.bpf.o\` that's \`${objStem}\`. */
bpf
  .bind("events", { kind: "ringbuf", btf_struct: "${stem}_event" })
  .bind("${objStem}.bss", { kind: "data" })
  .bind("${objStem}.rodata", { kind: "data" })
  .attach("${stem}_count", {});

const control = await bpf.start();
console.log(style.green(\`${name} started: \${control.id}\`));

const events = new RingBuf(control, "events");
const bss = new DataSec(control, "${objStem}.bss");

const sub = await events.subscribe(
  ({ ${stem}_event: ev }) => {
    console.log(
      style.dim(\`[\${ev.ts_ns}] if=\${ev.ifindex} len=\${ev.len}\`),
    );
  },
  (err) => console.error(style.red(\`ringbuf error: \${err.message}\`)),
);

const deadline = Date.now() + RUN_SECONDS * 1_000;
while (Date.now() < deadline) {
  const packets_seen = await bss.read("packets_seen");
  console.log(style.cyan(\`packets_seen=\${packets_seen}\`));
  await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
}

await sub.unsubscribe();
await control.stop();
console.log(style.green("${name} stopped."));
`;
}

function readmeTemplate(name) {
  return `# ${name}

Scaffolded by \`example/bootstrap\`. Replace this header with a real
description of what the example demonstrates.

The starter wires an XDP noop that:

- Counts every packet into a \`__u64\` in \`.bss\` (\`packets_seen\`).
- Emits a small ringbuf event per packet up to an \`event_budget\`
  threshold pulled from \`.rodata\`.

## Build

\`\`\`sh
make
\`\`\`

On macOS, run \`make\` inside the Lima VM:

\`\`\`sh
lima/scripts/vm_shell.sh yeet.debian-13 make
\`\`\`

## Run

\`main.js\` ships with a \`#!/usr/bin/env -S yeet run\` shebang and is
chmod +x, so either form works:

\`\`\`sh
./main.js
yeet run ./example/${name}
\`\`\`
`;
}
