#!/usr/bin/env bash
# Generated by example/bootstrap. Higher-level installer for Linux,
# invoked after rolecall confirms os=Linux (and implicitly bash=OK,
# since the script tree gates on it).
#
# Bash is fine inside the gated install body below. But this file is
# *sourced* by rolecall.sh from POSIX /bin/sh to harvest linux_probe,
# so the function definitions and any top-level statements above the
# gate must stay POSIX-parseable. Restrict bash-only syntax ([[ ]],
# arrays, <( ), etc.) to the install body.
set -eu

# Source common.sh only if not already loaded. When rolecall.sh
# sources this file for probe harvesting, common.sh is already loaded
# and $0 belongs to the caller — so a fresh source would resolve to
# the wrong path. (Avoid `command -v log`: it can collide with system
# utilities of the same name on some platforms.)
[ "${COMMON_SH_LOADED:-0}" = "1" ] || . "$(dirname "$0")/../common.sh"

# linux_probe — add Linux-only entries to ROLECALL_RESULTS. Called by
# rolecall.sh's default suite after detecting os=Linux, and reusable
# from anywhere that has rolecall_for in scope.
linux_probe() {
    # Package managers / init / runtime — install scripts pick one.
    rolecall_for apt-get dnf apk pacman systemctl docker
    # Build & BPF toolchain (re-checks clang/gcc deliberately so the
    # Linux-specific assertion appears in ROLECALL_RESULTS alongside
    # the bpftool result).
    rolecall_for gcc clang bpftool
}

# When sourced with ROLECALL_PROBE_ONLY=1 (rolecall.sh does this to
# harvest the probe function), skip the install body entirely.
if [ "${ROLECALL_PROBE_ONLY:-0}" != "1" ]; then
    log "linux installer"

    # Pick a package-install command based on the rolecall probes.
    case " $ROLECALL_RESULTS " in
        *" apt-get=OK "*) _pkg_install="sudo apt-get install -y" ;;
        *" dnf=OK "*)     _pkg_install="sudo dnf install -y" ;;
        *" apk=OK "*)     _pkg_install="apk add" ;;
        *" pacman=OK "*)  _pkg_install="sudo pacman -S --noconfirm" ;;
        *)                _pkg_install="" ;;
    esac

    # Collect tools that came back as FAIL and need installation.
    _needed=""
    for _tool in clang bpftool; do
        case " $ROLECALL_RESULTS " in
            *" ${_tool}=FAIL "*) _needed="$_needed $_tool" ;;
        esac
    done

    if [ -n "$_needed" ]; then
        if [ -n "$_pkg_install" ]; then
            cprintf '%[yellow]missing:%[/]%s\n' "$_needed"
            # Flip to the real install when ready:
            #   $_pkg_install $_needed
            log "would run: $_pkg_install$_needed"
        else
            die "missing tools ($_needed) and no supported package manager"
        fi
    else
        log "all linux build tools present"
    fi

    # Linux uses the native toolchain — no docker indirection needed.
    # Write linux/env.sh so the Makefile's $(CLANG)/$(BPFTOOL) lookup
    # resolves to plain binaries on PATH.
    _env_dir=$(dirname "$0")/linux
    mkdir -p "$_env_dir"
    cat > "$_env_dir/env.sh" <<'EOF'
# Generated by scripts/installers/linux.sh. Native toolchain — no
# container indirection on Linux. Source from project root.
CLANG="clang"
BPFTOOL="bpftool"
export CLANG BPFTOOL
EOF
    log "wrote $_env_dir/env.sh"
fi
