#!/usr/bin/env bash
# Generated by example/bootstrap. Higher-level installer for macOS,
# invoked after rolecall confirms os=Darwin (and implicitly bash=OK,
# since the script tree gates on it).
#
# Bash is fine inside the gated install body below. But this file is
# *sourced* by rolecall.sh from POSIX /bin/sh to harvest macos_probe,
# so the function definitions and any top-level statements above the
# gate must stay POSIX-parseable. Restrict bash-only syntax ([[ ]],
# arrays, <( ), etc.) to the install body.
set -eu

# Source common.sh only if not already loaded. When rolecall.sh
# sources this file for probe harvesting, common.sh is already loaded
# and $0 belongs to the caller — so a fresh source would resolve to
# the wrong path. (Don't gate on `command -v log`: macOS has its own
# /usr/bin/log utility, which would shadow the check.)
[ "${COMMON_SH_LOADED:-0}" = "1" ] || . "$(dirname "$0")/../common.sh"

# macos_probe — add macOS-only entries to ROLECALL_RESULTS. Called by
# rolecall.sh's default suite after detecting os=Darwin, and reusable
# from anywhere that has rolecall_for in scope.
macos_probe() {
    rolecall_for brew xcode-select sw_vers lima qemu docker
}

# build_container — invoked when docker is available. Builds the
# image from scripts/installers/macos/Dockerfile, tags it as
# test:latest, and writes scripts/installers/macos/env.sh with
# CLANG and BPFTOOL pointing at `docker run -it` invocations of the
# image. Source that env file from the project root to use the
# containerized tools transparently.
build_container() {
    _container_dir=$(dirname "$0")/macos
    _env_file="$_container_dir/env.sh"
    log "build_container: building test:latest from $_container_dir (this can take a minute on first run)"

    # The actual image build. `set -eu` aborts the installer if this
    # fails, which intentionally skips the env.sh write below.
    docker build -t test:latest "$_container_dir"

    log "build_container: image built"

    # Quoted heredoc — $PWD stays literal so it expands at source
    # time, letting the wrapper mount whatever cwd the caller has.
    cat > "$_env_file" <<'EOF'
# Generated by scripts/installers/macos.sh build_container().
# Source from the project root to get CLANG and BPFTOOL pointing at
# the build container with the project mounted at /workspace:
#   . scripts/installers/macos/env.sh
#   $CLANG -v
#   $BPFTOOL prog list
CLANG="docker run --rm -it -v $PWD:/workspace -w /workspace test:latest clang"
BPFTOOL="docker run --rm -it -v $PWD:/workspace -w /workspace test:latest bpftool"
export CLANG BPFTOOL
EOF
    log "build_container: wrote $_env_file"
}

# When sourced with ROLECALL_PROBE_ONLY=1 (rolecall.sh does this to
# harvest the probe function), skip the install body entirely.
if [ "${ROLECALL_PROBE_ONLY:-0}" != "1" ]; then
    log "macos installer"

    # Docker remediation. Reaches us via install.sh, which exports
    # ROLECALL_RESULTS before `exec`-ing this script.
    case " $ROLECALL_RESULTS " in
        *" docker=FAIL "*)
            case " $ROLECALL_RESULTS " in
                *" brew=OK "*)
                    cprintf '%[yellow]docker missing%[/] — installing via homebrew\n'
                    # Flip to the real install once you trust the script
                    # to do destructive things unattended:
                    #   brew install --cask docker
                    log 'would run: brew install --cask docker'
                    ;;
                *)
                    die "docker missing and no homebrew to install it; see https://docs.docker.com/desktop/install/mac-install/"
                    ;;
            esac
            ;;
        *" docker=OK "*)
            log "docker present"
            build_container
            ;;
        *)
            log "docker probe not in map; run via scripts/install.sh"
            ;;
    esac

    # TODO: rest of test's macOS install steps. Example shape:
    #
    #   case " $ROLECALL_RESULTS " in
    #       *" brew=FAIL "*) die "homebrew required" ;;
    #   esac
    #   brew install <packages>
    #   ./bin/test --post-install
    #
    # Branch further on `arch=arm64` vs `arch=x86_64` if the toolchain
    # differs per architecture.

    cprintf '%[yellow]stub:%[/] scripts/installers/macos.sh not fully implemented yet\n'
fi
