// SPDX-License-Identifier: GPL-2.0
//
// Generated by example/bootstrap. Minimal XDP noop that emits a
// ringbuf event per packet and bumps a .bss counter. Replace with
// your own program logic.

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "GPL";

struct __STEM___event {
	__u64 ts_ns;
	__u32 ifindex;
	__u32 len;
};

struct {
	__uint(type, BPF_MAP_TYPE_RINGBUF);
	__uint(max_entries, 1 << 16);
} events SEC(".maps");

__u64 packets_seen = 0;
const volatile __u32 event_budget = 16;

SEC("xdp")
int __STEM___count(struct xdp_md *ctx)
{
	__sync_fetch_and_add(&packets_seen, 1);

	if (packets_seen > event_budget)
		return XDP_PASS;

	struct __STEM___event *ev = bpf_ringbuf_reserve(&events, sizeof(*ev), 0);
	if (!ev)
		return XDP_PASS;

	ev->ts_ns = bpf_ktime_get_ns();
	ev->ifindex = ctx->ingress_ifindex;
	ev->len = (__u32)(ctx->data_end - ctx->data);
	bpf_ringbuf_submit(ev, 0);

	return XDP_PASS;
}
