# scripts/common.sh — generated by example/bootstrap. Source me from
# other scripts in this directory; do not run directly. POSIX sh.

# Marker so callers can guard re-sourcing without relying on
# `command -v <fn>` (which collides with system tools like macOS's
# /usr/bin/log).
COMMON_SH_LOADED=1

PROJECT_NAME="__NAME__"
PROJECT_ROOT=$(cd "$(dirname "$0")/.." && pwd)

# cprintf <format> [args...]
# Like printf, but the format string supports inline color tags:
#   %[red] %[green] %[yellow] %[blue] %[magenta] %[cyan] %[bold] %[dim]
#   %[/]   — reset
# Tags are substituted with ANSI escapes when the target fd (stdout of
# the call) is a TTY, and stripped otherwise. So `cprintf '...' >&2`
# correctly tracks whether stderr is a terminal.
cprintf() {
    _fmt="$1"; shift
    if [ -t 1 ]; then
        _esc=$(printf '\033')
        _fmt=$(printf '%s' "$_fmt" | sed \
            -e "s|%\[red\]|${_esc}[31m|g" \
            -e "s|%\[green\]|${_esc}[32m|g" \
            -e "s|%\[yellow\]|${_esc}[33m|g" \
            -e "s|%\[blue\]|${_esc}[34m|g" \
            -e "s|%\[magenta\]|${_esc}[35m|g" \
            -e "s|%\[cyan\]|${_esc}[36m|g" \
            -e "s|%\[bold\]|${_esc}[1m|g" \
            -e "s|%\[dim\]|${_esc}[2m|g" \
            -e "s|%\[/\]|${_esc}[0m|g")
    else
        _fmt=$(printf '%s' "$_fmt" | sed 's|%\[[a-z/]*\]||g')
    fi
    # shellcheck disable=SC2059
    printf "$_fmt" "$@"
}

log() { cprintf '%[green][%s]%[/] %s\n' "info" "$*"; }
die() { cprintf '%[red]error:%[/] %s\n' "$*" >&2; exit 1; }
