#!/bin/sh
# Generated by example/bootstrap. Installer entry point: runs rolecall
# to populate ROLECALL_RESULTS, then execs the OS-specific installer
# under installers/.
set -eu

_here=$(dirname "$0")

. "$_here/common.sh"

# Clear $@ before sourcing so rolecall.sh runs its default suite
# instead of treating our own argv as a focused-check request.
set --
. "$_here/rolecall.sh"

# Export the populated map so the dispatched installer (a fresh
# process after `exec`) inherits it via env.
export ROLECALL_RESULTS

case " $ROLECALL_RESULTS " in
    *" os=Darwin "*) exec "$_here/installers/macos.sh" ;;
    *" os=Linux "*)  exec "$_here/installers/linux.sh" ;;
    *)               die "no installer for this OS (rolecall: $ROLECALL_RESULTS)" ;;
esac
