#!/usr/bin/env -S yeet run
/* __NAME__ — generated by example/bootstrap.
 *
 * Replace this header with a real description once the example does
 * something. Build the object first (inside Lima on macOS):
 *
 *   make
 *
 * Then run from the project root (pick whichever is convenient):
 *
 *   ./bin/__SLUG__     # launcher: execs yeet run against ./src
 *   ./src/main.js      # main.js is chmod +x, shebang resolves to yeet
 *   yeet run ./src
 */

import bpf from "../build/__STEM__.bpf.o";
import { DataSec, RingBuf } from "yeet:bpf";

const RUN_SECONDS = 10;
const POLL_INTERVAL_MS = 1_000;

/* libbpf names the implicit data-section maps `<obj>.bss` / `<obj>.data`
 * where `<obj>` is the BPF object's stem truncated to 8 chars. For
 * `__STEM__.bpf.o` that's `__OBJ_STEM__`. */
bpf
  .bind("events", { kind: "ringbuf", btf_struct: "__STEM___event" })
  .bind("__OBJ_STEM__.bss", { kind: "data" })
  .bind("__OBJ_STEM__.rodata", { kind: "data" })
  .attach("__STEM___count", {});

const control = await bpf.start();
console.log(style.green(`__NAME__ started: ${control.id}`));

const events = new RingBuf(control, "events");
const bss = new DataSec(control, "__OBJ_STEM__.bss");

const sub = await events.subscribe(
  ({ __STEM___event: ev }) => {
    console.log(
      style.dim(`[${ev.ts_ns}] if=${ev.ifindex} len=${ev.len}`),
    );
  },
  (err) => console.error(style.red(`ringbuf error: ${err.message}`)),
);

const deadline = Date.now() + RUN_SECONDS * 1_000;
while (Date.now() < deadline) {
  const packets_seen = await bss.read("packets_seen");
  console.log(style.cyan(`packets_seen=${packets_seen}`));
  await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
}

await sub.unsubscribe();
await control.stop();
console.log(style.green("__NAME__ stopped."));
