#!/bin/sh
# Generated by example/bootstrap. POSIX sh only — this script is the
# bottom of the toolchain stack and assumes nothing beyond POSIX.
# Higher-level installers source it (or re-run + parse) and read
# ROLECALL_RESULTS to decide what they can launch next.
#
# Invocation:
#   ./scripts/rolecall.sh                  → run the full default suite
#   ./scripts/rolecall.sh os bash brew     → check only these names
#                                            (uses the mapping in
#                                            rolecall_for, falls back
#                                            to PATH lookup)
set -eu

. "$(dirname "$0")/common.sh"

# Two ways to fill the map:
#   rolecall <cmd1> [cmd2 ...]   — PATH lookup; store "name=OK" / "name=FAIL"
#   detect   <label> <cmd ...>   — capture first stdout line; store "label=<value>"
# Both append to ROLECALL_RESULTS as space-separated key=value pairs.
# Query: case " $ROLECALL_RESULTS " in *" key=val "*) ... ;; esac

ROLECALL_RESULTS=""

rolecall() {
    for _cmd in "$@"; do
        # `command -v` does PATH/builtin lookup without executing — safe
        # for entries like `bash` that would otherwise block on stdin.
        if command -v "$_cmd" >/dev/null 2>&1; then
            cprintf '  %-20s %[green]OK%[/]\n' "$_cmd"
            ROLECALL_RESULTS="${ROLECALL_RESULTS}${_cmd}=OK "
        else
            cprintf '  %-20s %[red]FAIL%[/]\n' "$_cmd"
            ROLECALL_RESULTS="${ROLECALL_RESULTS}${_cmd}=FAIL "
        fi
    done
}

detect() {
    _label=$1; shift
    if _val=$("$@" </dev/null 2>/dev/null) && [ -n "$_val" ]; then
        # First line; collapse internal whitespace so the value is one
        # token (the map is space-delimited).
        _val=$(printf '%s' "$_val" | head -n 1 | tr -d '\n\r' | tr ' \t' '_')
        cprintf '  %-20s %[cyan]%s%[/]\n' "$_label" "$_val"
        ROLECALL_RESULTS="${ROLECALL_RESULTS}${_label}=${_val} "
    else
        cprintf '  %-20s %[red]?%[/]\n' "$_label"
        ROLECALL_RESULTS="${ROLECALL_RESULTS}${_label}=? "
    fi
}

# rolecall_for <name1> [name2 ...] — check each named item using the
# built-in mapping (os/arch/kernel route to `detect`; anything else
# falls through to `rolecall` PATH lookup). Exposed so higher-level
# scripts can do focused checks after sourcing this file, e.g.:
#   . ./scripts/rolecall.sh    # populates the full map
#   rolecall_for bash brew     # add a couple more entries on demand
rolecall_for() {
    for _q in "$@"; do
        case "$_q" in
            os)     detect os     uname -s ;;
            arch)   detect arch   uname -m ;;
            kernel) detect kernel uname -r ;;
            *)      rolecall "$_q" ;;
        esac
    done
}

cprintf "%[yellow]Rolecall%[/]\n"

if [ "$#" -gt 0 ]; then
    rolecall_for "$@"
else
    rolecall_for os arch kernel
    rolecall_for bash zsh dash ksh
    rolecall_for make clang gcc git curl tar

    # OS-specific probes: source the matching installer (with the
    # PROBE_ONLY gate so its install body doesn't fire) and call its
    # <os>_probe function to add platform-only entries to the map.
    # POSIX special-builtin assignment semantics let the gate var
    # persist past the `.` source, so unset it before any later exec
    # would inherit it (e.g. install.sh dispatching to the installer).
    _here=$(dirname "$0")
    case " $ROLECALL_RESULTS " in
        *" os=Darwin "*)
            if [ -f "$_here/installers/macos.sh" ]; then
                ROLECALL_PROBE_ONLY=1 . "$_here/installers/macos.sh"
                unset ROLECALL_PROBE_ONLY
                macos_probe
            fi
            ;;
        *" os=Linux "*)
            if [ -f "$_here/installers/linux.sh" ]; then
                ROLECALL_PROBE_ONLY=1 . "$_here/installers/linux.sh"
                unset ROLECALL_PROBE_ONLY
                linux_probe
            fi
            ;;
    esac
fi
